In [22]:
import pandas as pd
from datetime import datetime

In [23]:
df = pd.read_csv("C:/Users/Aashi Khanna/Downloads/Layoffs.fyi  - Tech Layoffs Tracker.csv")
df

,Company,Location HQ,# Laid Off,Date,%,Industry,Source,Stage,$ Raised (mm),Country,Date Added
0,LeddarTech,"Quebec,Non-U.S.",138.0,5/22/2025,95%,Transportation,https://betakit.com/leddartech-cuts-95-percent...,Post-IPO,$402,Canada,5/23/2025
1,Climeworks,"Zurich,Non-U.S.",106.0,5/21/2025,22%,Energy,https://www.bloomberg.com/news/articles/2025-0...,Private Equity,$734,Switzerland,5/23/2025
2,Builder.ai,"London,Non-U.S.",NaN,5/20/2025,100%,AI,https://techcrunch.com/2025/05/20/once-worth-o...,Series D,$445,United States,5/23/2025
3,Blink Charging,Baltimore,NaN,5/19/2025,20%,Other,https://blinkcharging.com/news/blink-charging-...,Post-IPO,$110,United States,5/23/2025
4,VerSe Innovation copy,"Bengaluru,Non-U.S.",350.0,5/18/2025,NaN,Media,https://inc42.com/buzz/josh-dailyhunt-parent-v...,Series J,$1700,India,5/23/2025
...,...,...,...,...,...,...,...,...,...,...,...
4067,Service,Los Angeles,NaN,3/16/2020,100%,Travel,https://techcrunch.com/2020/03/16/travel-savin...,Seed,$5,United States,8/31/2020
4068,HopSkipDrive,Los Angeles,8.0,3/13/2020,10%,Transportation,https://layoffs.fyi/2020/04/02/hopskipdrive-la...,Unknown,$45,United States,4/3/2020
4069,Panda Squad,SF Bay Area,6.0,3/13/2020,75%,Consumer,https://twitter.com/danielsinger/status/123854...,Seed,$1,United States,4/17/2020
4070,Tamara Mellon,Los Angeles,20.0,3/12/2020,40%,Retail,https://layoffs.fyi/list/tamara-mellon/,Series C,$90,United States,3/31/2020
4071,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,https://www.bizjournals.com/louisville/news/20...,Series A,$12,United States,3/31/2020

In [24]:
df.drop(columns=['Source'], inplace=True)

In [25]:
df

,Company,Location HQ,# Laid Off,Date,%,Industry,Stage,$ Raised (mm),Country,Date Added
0,LeddarTech,"Quebec,Non-U.S.",138.0,5/22/2025,95%,Transportation,Post-IPO,$402,Canada,5/23/2025
1,Climeworks,"Zurich,Non-U.S.",106.0,5/21/2025,22%,Energy,Private Equity,$734,Switzerland,5/23/2025
2,Builder.ai,"London,Non-U.S.",NaN,5/20/2025,100%,AI,Series D,$445,United States,5/23/2025
3,Blink Charging,Baltimore,NaN,5/19/2025,20%,Other,Post-IPO,$110,United States,5/23/2025
4,VerSe Innovation copy,"Bengaluru,Non-U.S.",350.0,5/18/2025,NaN,Media,Series J,$1700,India,5/23/2025
...,...,...,...,...,...,...,...,...,...,...
4067,Service,Los Angeles,NaN,3/16/2020,100%,Travel,Seed,$5,United States,8/31/2020
4068,HopSkipDrive,Los Angeles,8.0,3/13/2020,10%,Transportation,Unknown,$45,United States,4/3/2020
4069,Panda Squad,SF Bay Area,6.0,3/13/2020,75%,Consumer,Seed,$1,United States,4/17/2020
4070,Tamara Mellon,Los Angeles,20.0,3/12/2020,40%,Retail,Series C,$90,United States,3/31/2020
4071,EasyPost,Salt Lake City,75.0,3/11/2020,NaN,Logistics,Series A,$12,United States,3/31/2020

In [26]:
print(df.dtypes)

Company           object
Location HQ       object
# Laid Off       float64
Date              object
%                 object
Industry          object
Stage             object
$ Raised (mm)     object
Country           object
Date Added        object
dtype: object

In [27]:
# Convert 'Date' to datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Keep only records from 2025
df = df[df['Date'].dt.year == 2025]

# Create 'Month' column in format: '2025-01', '2025-02', etc.
df['Month'] = df['Date'].dt.strftime('%B') 

df

C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2936198697.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Date'].dt.strftime('%B')

,Company,Location HQ,# Laid Off,Date,%,Industry,Stage,$ Raised (mm),Country,Date Added,Month
0,LeddarTech,"Quebec,Non-U.S.",138.0,2025-05-22,95%,Transportation,Post-IPO,$402,Canada,5/23/2025,May
1,Climeworks,"Zurich,Non-U.S.",106.0,2025-05-21,22%,Energy,Private Equity,$734,Switzerland,5/23/2025,May
2,Builder.ai,"London,Non-U.S.",NaN,2025-05-20,100%,AI,Series D,$445,United States,5/23/2025,May
3,Blink Charging,Baltimore,NaN,2025-05-19,20%,Other,Post-IPO,$110,United States,5/23/2025,May
4,VerSe Innovation copy,"Bengaluru,Non-U.S.",350.0,2025-05-18,NaN,Media,Series J,$1700,India,5/23/2025,May
...,...,...,...,...,...,...,...,...,...,...,...
140,Aqua Security,Boston,NaN,2025-01-07,NaN,Security,Series E,$325,United States,1/8/2025,January
141,Cloud Software Group,SF Bay Area,NaN,2025-01-07,NaN,Other,Unknown,NaN,United States,1/12/2025,January
142,Microsoft,Seattle,NaN,2025-01-07,NaN,Other,Post-IPO,$1,United States,1/12/2025,January
143,SolarEdge,"Tel Aviv,Non-U.S.",400.0,2025-01-06,NaN,Energy,Post-IPO,$155,Israel,1/8/2025,January
144,Level,New York City,NaN,2025-01-02,100%,Finance,Series B,$27,United States,1/4/2025,January

In [28]:
# Remove '%' symbol and convert to float
df['%'] = df['%'].str.replace('%', '', regex=False).astype(float)
df['%'] = df['%'].fillna(0.0)

# Remove '$' symbol from '$ Raised (mm)' and convert to float
df['$ Raised (mm)'] = (
    df['$ Raised (mm)']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace(',', '')  # Optional: remove commas if present
    .astype(float)
)
df['$ Raised (mm)'] = pd.to_numeric(df['$ Raised (mm)'], errors='coerce').fillna(0.0)

df['# Laid Off'] = df['# Laid Off'].fillna(0)
df['Industry'] = df['Industry'].fillna("Unknown")
df['Stage'] = df['Stage'].fillna("Unknown")
df['Location HQ'] = df['Location HQ'].fillna("Unknown")
df['Country'] = df['Country'].fillna("Unknown")

df

C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['%'] = df['%'].str.replace('%', '', regex=False).astype(float)
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['%'] = df['%'].fillna(0.0)
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['$ Raised (mm)'] = (
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['$ Raised (mm)'] = pd.to_numeric(df['$ Raised (mm)'], errors='coerce').fillna(0.0)
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['# Laid Off'] = df['# Laid Off'].fillna(0)
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Industry'] = df['Industry'].fillna("Unknown")
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Stage'] = df['Stage'].fillna("Unknown")
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Location HQ'] = df['Location HQ'].fillna("Unknown")
C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\2688106744.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].fillna("Unknown")

,Company,Location HQ,# Laid Off,Date,%,Industry,Stage,$ Raised (mm),Country,Date Added,Month
0,LeddarTech,"Quebec,Non-U.S.",138.0,2025-05-22,95.0,Transportation,Post-IPO,402.0,Canada,5/23/2025,May
1,Climeworks,"Zurich,Non-U.S.",106.0,2025-05-21,22.0,Energy,Private Equity,734.0,Switzerland,5/23/2025,May
2,Builder.ai,"London,Non-U.S.",0.0,2025-05-20,100.0,AI,Series D,445.0,United States,5/23/2025,May
3,Blink Charging,Baltimore,0.0,2025-05-19,20.0,Other,Post-IPO,110.0,United States,5/23/2025,May
4,VerSe Innovation copy,"Bengaluru,Non-U.S.",350.0,2025-05-18,0.0,Media,Series J,1700.0,India,5/23/2025,May
...,...,...,...,...,...,...,...,...,...,...,...
140,Aqua Security,Boston,0.0,2025-01-07,0.0,Security,Series E,325.0,United States,1/8/2025,January
141,Cloud Software Group,SF Bay Area,0.0,2025-01-07,0.0,Other,Unknown,0.0,United States,1/12/2025,January
142,Microsoft,Seattle,0.0,2025-01-07,0.0,Other,Post-IPO,1.0,United States,1/12/2025,January
143,SolarEdge,"Tel Aviv,Non-U.S.",400.0,2025-01-06,0.0,Energy,Post-IPO,155.0,Israel,1/8/2025,January
144,Level,New York City,0.0,2025-01-02,100.0,Finance,Series B,27.0,United States,1/4/2025,January

In [30]:
df['Layoff Region'] = df['Country'].apply(lambda x: 'US' if str(x).strip().upper() == 'UNITED STATES' else 'Non-US')
df

C:\Users\Aashi Khanna\AppData\Local\Temp\ipykernel_14428\132921258.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Layoff Region'] = df['Country'].apply(lambda x: 'US' if str(x).strip().upper() == 'UNITED STATES' else 'Non-US')

,Company,Location HQ,# Laid Off,Date,%,Industry,Stage,$ Raised (mm),Country,Date Added,Month,Layoff Region
0,LeddarTech,"Quebec,Non-U.S.",138.0,2025-05-22,95.0,Transportation,Post-IPO,402.0,Canada,5/23/2025,May,Non-US
1,Climeworks,"Zurich,Non-U.S.",106.0,2025-05-21,22.0,Energy,Private Equity,734.0,Switzerland,5/23/2025,May,Non-US
2,Builder.ai,"London,Non-U.S.",0.0,2025-05-20,100.0,AI,Series D,445.0,United States,5/23/2025,May,US
3,Blink Charging,Baltimore,0.0,2025-05-19,20.0,Other,Post-IPO,110.0,United States,5/23/2025,May,US
4,VerSe Innovation copy,"Bengaluru,Non-U.S.",350.0,2025-05-18,0.0,Media,Series J,1700.0,India,5/23/2025,May,Non-US
...,...,...,...,...,...,...,...,...,...,...,...,...
140,Aqua Security,Boston,0.0,2025-01-07,0.0,Security,Series E,325.0,United States,1/8/2025,January,US
141,Cloud Software Group,SF Bay Area,0.0,2025-01-07,0.0,Other,Unknown,0.0,United States,1/12/2025,January,US
142,Microsoft,Seattle,0.0,2025-01-07,0.0,Other,Post-IPO,1.0,United States,1/12/2025,January,US
143,SolarEdge,"Tel Aviv,Non-U.S.",400.0,2025-01-06,0.0,Energy,Post-IPO,155.0,Israel,1/8/2025,January,Non-US
144,Level,New York City,0.0,2025-01-02,100.0,Finance,Series B,27.0,United States,1/4/2025,January,US

In [31]:
df.to_csv("2025_Tech_Layoffs_Cleaned.csv", index=False)